--- 
javascripts: 
- base: 
  - prototype
  - effects
  - dragdrop
  - controls
  - textInputWithDefaultText
  - texpand
  - application
  - tabber
  - boxover
  - redbox
  - tablekit
  - p7exp
  - xregexp-min
stylesheets: 
- base:
  - reset-fonts
  - p7exp
  - styles
  - redbox
  - rounded-corners
  - ratings
